INFO:tensorflow:vocabulary_size = 543060 in UID is inferred from the number of elements in the vocabulary_file ./data/uid_voc.txt.
INFO:tensorflow:vocabulary_size = 367983 in ITEM is inferred from the number of elements in the vocabulary_file ./data/mid_voc.txt.
INFO:tensorflow:vocabulary_size = 1601 in CATEGORY is inferred from the number of elements in the vocabulary_file ./data/cat_voc.txt.
INFO:tensorflow:vocabulary_size = 367983 in HISTORY_ITEM is inferred from the number of elements in the vocabulary_file ./data/mid_voc.txt.
INFO:tensorflow:vocabulary_size = 1601 in HISTORY_CATEGORY is inferred from the number of elements in the vocabulary_file ./data/cat_voc.txt.
INFO:tensorflow:vocabulary_size = 367983 in NOCLK_HISTORY_ITEM is inferred from the number of elements in the vocabulary_file ./data/mid_voc.txt.
INFO:tensorflow:vocabulary_size = 1601 in NOCLK_HISTORY_CATEGORY is inferred from the number of elements in the vocabulary_file ./data/cat_voc.txt.
INFO:tensorflow:Parsing ./data/local_train_splitByUser
INFO:tensorflow:Parsing ./data/local_test_splitByUser
2022-03-10 10:52:05.142263: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1900000000 Hz
2022-03-10 10:52:05.144116: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7effdb6f6f00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2022-03-10 10:52:05.144147: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Using TensorFlow version 1.15.5
Checking dataset
Numbers of training dataset is 1086120
Numbers of test dataset is 121216
Saving model checkpoints to /2022-03-10-10-51-36/dien_deeprec_fp32
Traceback (most recent call last):
  File "train.py", line 889, in <module>
    main()
  File "train.py", line 809, in main
    writer = tf.summary.FileWriter(checkpoint_dir, sess.graph)
  File "/home/shanlin/deeprec/lib64/python3.6/site-packages/tensorflow_core/python/summary/writer/writer.py", line 367, in __init__
    filename_suffix)
  File "/home/shanlin/deeprec/lib64/python3.6/site-packages/tensorflow_core/python/summary/writer/event_file_writer.py", line 67, in __init__
    gfile.MakeDirs(self._logdir)
  File "/home/shanlin/deeprec/lib64/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 438, in recursive_create_dir
    recursive_create_dir_v2(dirname)
  File "/home/shanlin/deeprec/lib64/python3.6/site-packages/tensorflow_core/python/lib/io/file_io.py", line 453, in recursive_create_dir_v2
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(path))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /2022-03-10-10-51-36; Permission denied
